SELECT date_format(SALES_DATE, '%Y-%m-%d') as SALES_DATE,
PRODUCT_ID, 
USER_ID,
SALES_AMOUNT
FROM ONLINE_SALE
WHERE YEAR(SALES_DATE) = 2022
AND MONTH(SALES_DATE) = 3

union all

SELECT date_format(SALES_DATE, '%Y-%m-%d') as SALES_DATE,
PRODUCT_ID, 
NULL as USER_ID,
SALES_AMOUNT
FROM OFFLINE_SALE
WHERE YEAR(SALES_DATE) = 2022
AND MONTH(SALES_DATE) = 3

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;