SELECT a.ID as ID,
CASE
    WHEN a.per <= 0.25 THEN 'CRITICAL'
    WHEN a.per <= 0.50 THEN 'HIGH'
    WHEN a.per <= 0.75 THEN 'MEDIUM'
    ELSE 'LOW'
END as COLONY_NAME
FROM (SELECT ID,
    PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY desc) as per
    FROM ECOLI_DATA) as a
ORDER BY a.ID